package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Admins generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminId;
     private User user;
     private boolean allowed;
     private String userFullName;
     private Date userBirthDate;

    public Admin() {
    }

    public Admin(User user, boolean allowed, String userFullName, Date userBirthDate) {
       this.user = user;
       this.allowed = allowed;
       this.userFullName = userFullName;
       this.userBirthDate = userBirthDate;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public boolean isAllowed() {
        return this.allowed;
    }
    
    public void setAllowed(boolean allowed) {
        this.allowed = allowed;
    }
    public String getUserFullName() {
        return this.userFullName;
    }
    
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }
    public Date getUserBirthDate() {
        return this.userBirthDate;
    }
    
    public void setUserBirthDate(Date userBirthDate) {
        this.userBirthDate = userBirthDate;
    }




}


