package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Admins generated by hbm2java
 */
public class Admin extends User implements java.io.Serializable {


     private int UserID;
     private boolean allowed;
     private String userFullName;
     private Date userBirthDate;

    public Admin() {
    }

    public Admin(String username, String userPassword, Date userRegDate, String userEmail,boolean allowed, String userFullName, Date userBirthDate) {
       super(username, userPassword, userRegDate, userEmail); 
       this.allowed = allowed;
       this.userFullName = userFullName;
       this.userBirthDate = userBirthDate;
    }
    
    public void setUserID(int userID) {
        this.UserID = userID;
        super.setUserId(userID);
    }
   
    public Integer getUserID(){
        return this.UserID; 
    }
    
    public boolean getAllowed() {
        return this.allowed;
    }
    
    public void setAllowed(boolean allowed) {
        this.allowed = allowed;
    }
    
    public String getUserFullName() {
        return this.userFullName;
    }
    
    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }
    
    public Date getUserBirthDate() {
        return this.userBirthDate;
    }
    
    public void setUserBirthDate(Date userBirthDate) {
        this.userBirthDate = userBirthDate;
    }




}


