package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Albums generated by hbm2java
 */
public class Album  implements java.io.Serializable {


     private Integer albumId;
     private Artist artist;
     private String albumName;
     private Date albumYear;
     private byte[] albumThumbnail;
     private double albumPrice;
     private boolean albumVerified;
     private boolean albumRestricted;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<GenreAlbum> genreAlbums = new HashSet<GenreAlbum>(0);
     private Set<Track> tracks = new HashSet<Track>(0);

    public Album() {
    }

	
    public Album(Artist artist, String albumName, Date albumYear, byte[] albumThumbnail, double albumPrice, boolean albumVerified, boolean albumRestricted) {
        this.artist = artist;
        this.albumName = albumName;
        this.albumYear = albumYear;
        this.albumThumbnail = albumThumbnail;
        this.albumPrice = albumPrice;
        this.albumVerified = albumVerified;
        this.albumRestricted = albumRestricted;
    }
    public Album(Artist artist, String albumName, Date albumYear, byte[] albumThumbnail, double albumPrice, boolean albumVerified, boolean albumRestricted, Set<Review> reviews, Set<GenreAlbum> genreAlbums, Set<Track> tracks) {
       this.artist = artist;
       this.albumName = albumName;
       this.albumYear = albumYear;
       this.albumThumbnail = albumThumbnail;
       this.albumPrice = albumPrice;
       this.albumVerified = albumVerified;
       this.albumRestricted = albumRestricted;
       this.reviews = reviews;
       this.genreAlbums = genreAlbums;
       this.tracks = tracks;
    }
   
    public Integer getAlbumId() {
        return this.albumId;
    }
    
    public void setAlbumId(Integer albumId) {
        this.albumId = albumId;
    }
    public Artist getArtist() {
        return this.artist;
    }
    
    public void setArtist(Artist artist) {
        this.artist = artist;
    }
    public String getAlbumName() {
        return this.albumName;
    }
    
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }
    public Date getAlbumYear() {
        return this.albumYear;
    }
    
    public void setAlbumYear(Date albumYear) {
        this.albumYear = albumYear;
    }
    public byte[] getAlbumThumbnail() {
        return this.albumThumbnail;
    }
    
    public void setAlbumThumbnail(byte[] albumThumbnail) {
        this.albumThumbnail = albumThumbnail;
    }
    public double getAlbumPrice() {
        return this.albumPrice;
    }
    
    public void setAlbumPrice(double albumPrice) {
        this.albumPrice = albumPrice;
    }
    public boolean isAlbumVerified() {
        return this.albumVerified;
    }
    
    public void setAlbumVerified(boolean albumVerified) {
        this.albumVerified = albumVerified;
    }
    public boolean isAlbumRestricted() {
        return this.albumRestricted;
    }
    
    public void setAlbumRestricted(boolean albumRestricted) {
        this.albumRestricted = albumRestricted;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews; 
    }
    public Set<GenreAlbum> getGenreAlbums() {
        return this.genreAlbums;
    }
    
    public void setGenreAlbums(Set<GenreAlbum> genreAlbums) {
        this.genreAlbums = genreAlbums;
    }
    public Set<Track> getTracks() {
        return this.tracks;
    }
    
    public void setTracks(Set<Track> tracks) {
        this.tracks = tracks;
    }




}


