package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Artists generated by hbm2java
 */
public class Artist  implements java.io.Serializable {


     private Integer artistId;
     private User user;
     private String artistName;
     private Date artistRegDate;
     private String artistContactNumer;
     private int contractId;
     private Date sinceDate;
     private Set<Album> albums = new HashSet<Album>(0);
     private Set<Contract> contracts = new HashSet<Contract>(0);

    public Artist() {
    }

	
    public Artist(User user, String artistName, Date artistRegDate, String artistContactNumer, int contractId, Date sinceDate) {
        this.user = user;
        this.artistName = artistName;
        this.artistRegDate = artistRegDate;
        this.artistContactNumer = artistContactNumer;
        this.contractId = contractId;
        this.sinceDate = sinceDate;
    }
    public Artist(User user, String artistName, Date artistRegDate, String artistContactNumer, int contractId, Date sinceDate, Set<Album> albums, Set<Contract> contracts) {
       this.user = user;
       this.artistName = artistName;
       this.artistRegDate = artistRegDate;
       this.artistContactNumer = artistContactNumer;
       this.contractId = contractId;
       this.sinceDate = sinceDate;
       this.albums = albums;
       this.contracts = contracts;
    }
   
    public Integer getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getArtistName() {
        return this.artistName;
    }
    
    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }
    public Date getArtistRegDate() {
        return this.artistRegDate;
    }
    
    public void setArtistRegDate(Date artistRegDate) {
        this.artistRegDate = artistRegDate;
    }
    public String getArtistContactNumer() {
        return this.artistContactNumer;
    }
    
    public void setArtistContactNumer(String artistContactNumer) {
        this.artistContactNumer = artistContactNumer;
    }
    public int getContractId() {
        return this.contractId;
    }
    
    public void setContractId(int contractId) {
        this.contractId = contractId;
    }
    public Date getSinceDate() {
        return this.sinceDate;
    }
    
    public void setSinceDate(Date sinceDate) {
        this.sinceDate = sinceDate;
    }
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }
    public Set<Contract> getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }




}


