package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Artists generated by hbm2java
 */
public class Artist extends User implements java.io.Serializable {


     private int UserID;
     private String artistName;
     private Date artistRegDate;
     private String artistContactNumer;
     private int contractId;
     private Date sinceDate;
     private Set<Album> albums = new HashSet<Album>(0);
     private Set<Contract> contracts = new HashSet<Contract>(0);

    public Artist() {
    }

	
    public Artist(String username, String userPassword, Date userRegDate, String userEmail, String artistName, Date artistRegDate, String artistContactNumer, int contractId, Date sinceDate) {
        super(username, userPassword, userRegDate, userEmail); 
        this.artistName = artistName;
        this.artistRegDate = artistRegDate;
        this.artistContactNumer = artistContactNumer;
        this.contractId = contractId;
        this.sinceDate = sinceDate;
    }
    
    public Artist(String username, String userPassword, Date userRegDate, String userEmail, String artistName, Date artistRegDate, String artistContactNumer, int contractId, Date sinceDate, Set<Album> albums, Set<Contract> contracts) {
       super(username,userPassword, userRegDate, userEmail); 
       this.artistName = artistName;
       this.artistRegDate = artistRegDate;
       this.artistContactNumer = artistContactNumer;
       this.contractId = contractId;
       this.sinceDate = sinceDate;
       this.albums = albums;
       this.contracts = contracts;
    }
   
   public Integer getUserID(){
        return this.UserID; 
    }
    
    public void setUserID(int userId) {
        this.UserID = userId;
        super.setUserId(userId); 
    }
   
    public String getArtistName() {
        return this.artistName;
    }
    
    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }
    
    public Date getArtistRegDate() {
        return this.artistRegDate;
    }
    
    public void setArtistRegDate(Date artistRegDate) {
        this.artistRegDate = artistRegDate;
    }
    
    public String getArtistContactNumer() {
        return this.artistContactNumer;
    }
    
    public void setArtistContactNumer(String artistContactNumer) {
        this.artistContactNumer = artistContactNumer;
    }
    
    public int getContractId() {
        return this.contractId;
    }
    
    public void setContractId(int contractId) {
        this.contractId = contractId;
    }
    
    public Date getSinceDate() {
        return this.sinceDate;
    }
    
    public void setSinceDate(Date sinceDate) {
        this.sinceDate = sinceDate;
    }
    
    public Set<Album> getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Set<Album> albums) {
        this.albums = albums;
    }
    public Set<Contract> getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }




}


