package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Contracts generated by hbm2java
 */
public class Contract  implements java.io.Serializable {


     private Integer contractId;
     private Artist artist;
     private Date contractBeginDate;
     private Date contractEndDate;
     private double contractPrice;

    public Contract() {
    }

    public Contract(Artist artist, Date contractBeginDate, Date contractEndDate, double contractPrice) {
       this.artist = artist;
       this.contractBeginDate = contractBeginDate;
       this.contractEndDate = contractEndDate;
       this.contractPrice = contractPrice;
    }
   
    public Integer getContractId() {
        return this.contractId;
    }
    
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }
    public Artist getArtist() {
        return this.artist;
    }
    
    public void setArtist(Artist artist) {
        this.artist = artist;
    }
    public Date getContractBeginDate() {
        return this.contractBeginDate;
    }
    
    public void setContractBeginDate(Date contractBeginDate) {
        this.contractBeginDate = contractBeginDate;
    }
    public Date getContractEndDate() {
        return this.contractEndDate;
    }
    
    public void setContractEndDate(Date contractEndDate) {
        this.contractEndDate = contractEndDate;
    }
    public double getContractPrice() {
        return this.contractPrice;
    }
    
    public void setContractPrice(double contractPrice) {
        this.contractPrice = contractPrice;
    }




}


