package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Genres generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private Integer genreId;
     private int genreName;
     private Set<GenreAlbum> genreAlbums = new HashSet<GenreAlbum>(0);

    public Genre() {
    }

	
    public Genre(int genreName) {
        this.genreName = genreName;
    }
    public Genre(int genreName, Set<GenreAlbum> genreAlbums) {
       this.genreName = genreName;
       this.genreAlbums = genreAlbums;
    }
   
    public Integer getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }
    public int getGenreName() {
        return this.genreName;
    }
    
    public void setGenreName(int genreName) {
        this.genreName = genreName;
    }
    public Set<GenreAlbum> getGenreAlbums() {
        return this.genreAlbums;
    }
    
    public void setGenreAlbums(Set<GenreAlbum> genreAlbums) {
        this.genreAlbums = genreAlbums;
    }




}


