package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listeners generated by hbm2java
 */
public class Listener extends User implements java.io.Serializable {


     private int UserID;
     private String listenerFullName;
     private int credits;
     private Date listenerBirthDate;
     private Set<Review> reviews = new HashSet<Review>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Listener() {
    }
    
    public Listener(String username, String userPassword, Date userRegDate, String userEmail, String listenerFullName, int credits, Date listenerBirthDate) {
        super(username, userPassword, userRegDate, userEmail); 
        this.listenerFullName = listenerFullName;
        this.credits = credits;
        this.listenerBirthDate = listenerBirthDate;
    }
    public Listener(String username, String userPassword, Date userRegDate, String userEmail, String listenerFullName, int credits, Date listenerBirthDate, Set<Review> reviews, Set<Order> orders) {
       super(username, userPassword, userRegDate, userEmail);
       this.listenerFullName = listenerFullName;
       this.credits = credits;
       this.listenerBirthDate = listenerBirthDate;
       this.reviews = reviews;
       this.orders = orders;
    }
   
    public void setUserID(int userId) {
        this.UserID = userId;
        super.setUserId(userId);
    }
    
    public Integer getUserID(){
        /*return this.UserID; */
        return super.getUserId();
    }
    
    public String getListenerFullName() {
        return this.listenerFullName;
    }
    
    public void setListenerFullName(String listenerFullName) {
        this.listenerFullName = listenerFullName;
    }
    public int getCredits() {
        return this.credits;
    }
    
    public void setCredits(int credits) {
        this.credits = credits;
    }
    public Date getListenerBirthDate() {
        return this.listenerBirthDate;
    }
    
    public void setListenerBirthDate(Date listenerBirthDate) {
        this.listenerBirthDate = listenerBirthDate;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


