package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listeners generated by hbm2java
 */
public class Listener  implements java.io.Serializable {


     private Integer listenerId;
     private User user;
     private String listenerFullName;
     private int credits;
     private Date listenerBirthDate;
     private Set<Review> reviews  = new HashSet<Review>(0);
     private Set<Order> orders = new HashSet<Order>(0);

    public Listener() {
    }

	
    public Listener(User user, String listenerFullName, int credits, Date listenerBirthDate) {
        this.user = user;
        this.listenerFullName = listenerFullName;
        this.credits = credits;
        this.listenerBirthDate = listenerBirthDate;
    }
    public Listener(User user, String listenerFullName, int credits, Date listenerBirthDate, Set<Review> reviews, Set<Order> orders) {
       this.user = user;
       this.listenerFullName = listenerFullName;
       this.credits = credits;
       this.listenerBirthDate = listenerBirthDate;
       this.reviews = reviews;
       this.orders = orders;
    }
   
    public Integer getListenerId() {
        return this.listenerId;
    }
    
    public void setListenerId(Integer listenerId) {
        this.listenerId = listenerId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getListenerFullName() {
        return this.listenerFullName;
    }
    
    public void setListenerFullName(String listenerFullName) {
        this.listenerFullName = listenerFullName;
    }
    public int getCredits() {
        return this.credits;
    }
    
    public void setCredits(int credits) {
        this.credits = credits;
    }
    public Date getListenerBirthDate() {
        return this.listenerBirthDate;
    }
    
    public void setListenerBirthDate(Date listenerBirthDate) {
        this.listenerBirthDate = listenerBirthDate;
    }
    public Set<Review> getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }




}


