package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Listener listener;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Order() {
    }

	
    public Order (Listener listener) {
        this.listener = listener;
    }
    
    public Order(Listener listener, Set<OrderDetail> orderDetails) {
       this.listener = listener;
       this.orderDetails = orderDetails;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Listener getListener() {
        return this.listener;
    }
    
    public void setListener(Listener listener) {
        this.listener = listener;
    }
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }




}


