package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0



/**
 * Reviews generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private Integer reviewId;
     private Listener listeners;
     private Album albums;

    public Review() {
    }

    public Review(Listener listeners, Album albums) {
       this.listeners = listeners;
       this.albums = albums;
    }
   
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }
    public Listener getListeners() {
        return this.listeners;
    }
    
    public void setListeners(Listener listeners) {
        this.listeners = listeners;
    }
    public Album getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Album albums) {
        this.albums = albums;
    }




}


