package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0



/**
 * Reviews generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private Integer reviewId;
     private Listener listener;
     private Album album;
     private String reviewText;

    public Review() {
    }

    /*public Review(Listener listener, Album album) {
       this.listener = listener;
       this.album = album;
    }*/
    
    public Review(Listener listener, Album album, String ReviewText) {
       this.listener = listener;
       this.reviewText = ReviewText;
       this.album = album;
    }
   
    public Integer getReviewId() {
        return this.reviewId;
    }
    
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }
    public Listener getListener() {
        return this.listener;
    }
    
    public void setListener(Listener listener) {
        this.listener = listener;
    }
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }
    
    public String getReviewText(){
        return this.reviewText;
    }
    
    public void setReviewText(String reviewText){
        this.reviewText = reviewText;
    }
    




}


