package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tracks generated by hbm2java
 */
public class Track  implements java.io.Serializable {


     private Integer trackId;
     private Album album;
     private int trackName;
     private Date trackLength;
     private String trackGenre;
     private Double trackPrice;
     private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Track() {
    }

	
    public Track(Album album, int trackName, Date trackLength, String trackGenre) {
        this.album = album;
        this.trackName = trackName;
        this.trackLength = trackLength;
        this.trackGenre = trackGenre;
    }
    public Track(Album album, int trackName, Date trackLength, String trackGenre, Double trackPrice, Set<OrderDetail> orderDetails) {
       this.album = album;
       this.trackName = trackName;
       this.trackLength = trackLength;
       this.trackGenre = trackGenre;
       this.trackPrice = trackPrice;
       this.orderDetails = orderDetails;
    }
   
    public Integer getTrackId() {
        return this.trackId;
    }
    
    public void setTrackId(Integer trackId) {
        this.trackId = trackId;
    }
    public Album getAlbum() {
        return this.album;
    }
    
    public void setAlbum(Album album) {
        this.album = album;
    }
    public int getTrackName() {
        return this.trackName;
    }
    
    public void setTrackName(int trackName) {
        this.trackName = trackName;
    }
    public Date getTrackLength() {
        return this.trackLength;
    }
    
    public void setTrackLength(Date trackLength) {
        this.trackLength = trackLength;
    }
    public String getTrackGenre() {
        return this.trackGenre;
    }
    
    public void setTrackGenre(String trackGenre) {
        this.trackGenre = trackGenre;
    }
    public Double getTrackPrice() {
        return this.trackPrice;
    }
    
    public void setTrackPrice(Double trackPrice) {
        this.trackPrice = trackPrice;
    }
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }




}


