package Model;
// Generated 6-mrt-2014 11:07:43 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String userPassword;
     private Date userRegDate;
     private String userEmail;
     /*private Admin admin;
     private Artist artist;
     private Listener listener;*/

    public User() {
    }

	
    public User(String username, String userPassword, Date userRegDate, String userEmail) {
        this.username = username;
        this.userPassword = userPassword;
        this.userRegDate = userRegDate;
        this.userEmail = userEmail;
    }
    public User(String username, String userPassword, Date userRegDate, String userEmail,Admin admin, Artist artist, Listener listener) {
       this.username = username;
       this.userPassword = userPassword;
       this.userRegDate = userRegDate;
       this.userEmail = userEmail;
       /*this.admin = admin;
       this.artist = artist;
       this.listener = listener;*/
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Date getUserRegDate() {
        return this.userRegDate;
    }
    
    public void setUserRegDate(Date userRegDate) {
        this.userRegDate = userRegDate;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    /*public Admin getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Admin admin) {
        this.admin = admin;
    }
    public Artist getArtist() {
        return this.artist;
    }
    
    public void setArtist(Artist artist) {
        this.artist = artist;
    }
    public Listener getListener() {
        return this.listener;
    }
    
    public void setListener(Listener listener) {
        this.listener = listener;
    }*/




}


