package Model;
// Generated 27-feb-2014 12:19:32 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private String username;
     private String userPassword;
     private Date userRegDate;
     private String userEmail;
     private Set<Admin> admins = new HashSet<Admin>(0);
     private Set<Artist> artists = new HashSet<Artist>(0);
     private Set<Listener> listeners = new HashSet<Listener>(0);

    public User() {
    }

	
    public User(String username, String userPassword, Date userRegDate, String userEmail) {
        this.username = username;
        this.userPassword = userPassword;
        this.userRegDate = userRegDate;
        this.userEmail = userEmail;
    }
    public User(String username, String userPassword, Date userRegDate, String userEmail, Set<Admin> admins, Set<Artist> artists, Set<Listener> listeners) {
       this.username = username;
       this.userPassword = userPassword;
       this.userRegDate = userRegDate;
       this.userEmail = userEmail;
       this.admins = admins;
       this.artists = artists;
       this.listeners = listeners;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }
    public Date getUserRegDate() {
        return this.userRegDate;
    }
    
    public void setUserRegDate(Date userRegDate) {
        this.userRegDate = userRegDate;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }
    public Set<Artist> getArtists() {
        return this.artists;
    }
    
    public void setArtists(Set<Artist> artists) {
        this.artists = artists;
    }
    public Set<Listener> getListeners() {
        return this.listeners;
    }
    
    public void setListeners(Set<Listener> listeners) {
        this.listeners = listeners;
    }




}


